raise an OverflowError like micropython for too big a value
adafruit/Adafruit_CircuitPython_Ticks pull request #11
Opened 2024-07-30 16:45 UTC by jepler

This allows the micropython test "ticks_add" to succeed when the adafruit_ticks implementation of ticks_add is used.

2024-08-05 15:33 UTC, dhalbert requested changes

2024-08-05 15:33 UTC, dhalbert commented on adafruit_ticks.py
>      return (ticks + delta) % _TICKS_PERIOD
reuse existing half-period constant (which wasn't previously used, but was defined)
```suggestion
    if  -_TICKS_HALFPERIOD < delta < _TICKS_HALFPERIOD:
        return (ticks + delta) % _TICKS_PERIOD
     raise OverflowError("ticks interval overflow")
```

Check my boundaries so I'm not off by one on either side.

2024-08-09 17:15 UTC, jepler commented
I performed my (micropython's) ticks test with Dan's proposed change (corrected) and it passes so it's probably a correct transformation. Thanks @dhalbert

2024-08-09 21:05 UTC, dhalbert approved these changes
Thanks for the fix!

2024-08-09 21:05 UTC, merged